"""add offline sync fields

Revision ID: 0be260d69e7a
Revises: d8a5446c80c3
Create Date: 2026-01-15 19:34:04.953228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be260d69e7a'
down_revision: Union[str, Sequence[str], None] = 'd8a5446c80c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('screenings', sa.Column('local_id', sa.String(), nullable=True))
    op.add_column('screenings', sa.Column('device_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'device_created_at')
    op.drop_column('screenings', 'local_id')
    op.drop_column('screenings', 'device_id')
    # ### end Alembic commands ###
