"""add next_followup_due to screenings

Revision ID: 31c5a1b72572
Revises: 48afaca0a797
Create Date: 2026-01-15 21:01:44.407449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c5a1b72572'
down_revision: Union[str, Sequence[str], None] = '48afaca0a797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('next_followup_due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'next_followup_due')
    # ### end Alembic commands ###
