"""added docter review columns

Revision ID: 48afaca0a797
Revises: 0be260d69e7a
Create Date: 2026-01-15 19:45:40.924190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48afaca0a797'
down_revision: Union[str, Sequence[str], None] = '0be260d69e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('screenings', sa.Column('doctor_decision', sa.String(), nullable=True))
    op.add_column('screenings', sa.Column('doctor_notes', sa.String(), nullable=True))
    op.add_column('screenings', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'screenings', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenings', type_='foreignkey')
    op.drop_column('screenings', 'reviewed_at')
    op.drop_column('screenings', 'doctor_notes')
    op.drop_column('screenings', 'doctor_decision')
    op.drop_column('screenings', 'reviewed_by')
    # ### end Alembic commands ###
