"""add referrals

Revision ID: 5df8ac561122
Revises: c21f3fdcbe92
Create Date: 2026-01-14 21:49:09.390264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df8ac561122'
down_revision: Union[str, Sequence[str], None] = 'c21f3fdcbe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('specialty', sa.String(), nullable=False))
    op.alter_column('referrals', 'screening_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referrals', 'urgency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referrals', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referrals', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referrals', 'urgency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referrals', 'screening_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('referrals', 'specialty')
    # ### end Alembic commands ###
