"""update screening probabilities

Revision ID: c21f3fdcbe92
Revises: 53dc63f7a520
Create Date: 2026-01-14 21:09:44.780566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21f3fdcbe92'
down_revision: Union[str, Sequence[str], None] = '53dc63f7a520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'image_url')
    # ### end Alembic commands ###
