"""add screening created_at

Revision ID: d8a5446c80c3
Revises: 1cea81547df3
Create Date: 2026-01-15 19:17:07.598273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a5446c80c3'
down_revision: Union[str, Sequence[str], None] = '1cea81547df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'created_at')
    # ### end Alembic commands ###
